'use client';

import { AnimatePresence, motion, useMotionValueEvent, useScroll, useSpring, useTransform } from 'framer-motion';
import { ArrowDownRight, ArrowRight, BatteryCharging, ChevronRight, Gauge, Menu, MoveRight, Play, X, Zap } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

const colors = [['Obsidian Black','#151719'],['Glacier Silver','#a9adb0'],['Aurora White','#e8e7e2'],['Midnight Blue','#183044'],['Ember Red','#6e1f25'],['Titanium Grey','#5d5d59']];
const tech = [['01','Adaptive Drive Intelligence','Reads the road, your intent, and the atmosphere—then quietly adjusts.'],['02','Predictive Navigation','Every route considered for pace, range, and charging before you depart.'],['03','360° Vision System','A composed view of the world around you, only when you need it.'],['04','Intelligent Cabin','Light, climate, and sound become one fluid, personal environment.'],['05','Over-the-air Evolution','Refinement and capability continue to mature over time.'],['06','Digital Key','A secure, seamless arrival designed around the devices you carry.']];
const scenes = [['01','Sculpted by airflow.'],['02','780 hp. Delivered in silence.'],['03','410 miles of effortless range.'],['04','Designed around the driver.']];

function MagneticButton({ children, dark=false, onClick }: { children: React.ReactNode; dark?: boolean; onClick?:()=>void }) {
  return <motion.button onClick={onClick} whileHover={{scale:1.035}} whileTap={{scale:.97}} transition={{type:'spring',stiffness:380,damping:22}} className={`magnetic ${dark?'dark':''}`}>{children}<ArrowRight size={16}/></motion.button>;
}

export default function VeloraExperience() {
  const root=useRef<HTMLDivElement>(null); const [menu,setMenu]=useState(false); const [modal,setModal]=useState(false); const [color,setColor]=useState('Obsidian Black'); const [wheel,setWheel]=useState('Aero 21'); const [interior,setInterior]=useState('Onyx'); const [speed,setSpeed]=useState(0); const [submitted,setSubmitted]=useState(false); const [scrolled,setScrolled]=useState(false); const [loaded,setLoaded]=useState(false); const [mode,setMode]=useState('Touring'); const [temperature,setTemperature]=useState(68);
  const {scrollYProgress}=useScroll(); const progress=useSpring(scrollYProgress,{stiffness:100,damping:28}); const heroY=useTransform(scrollYProgress,[0,.13],[0,130]); const selected=colors.find(c=>c[0]===color)?.[1]??'#151719';
  useMotionValueEvent(scrollYProgress,'change',()=>setScrolled(window.scrollY>40));
  useEffect(()=>{const id=setTimeout(()=>setLoaded(true),900);return()=>clearTimeout(id)},[]);
  useEffect(()=>{const saved=localStorage.getItem('velora-config'); if(saved){try{const v=JSON.parse(saved); setColor(v.color);setWheel(v.wheel);setInterior(v.interior)}catch{}}},[]);
  useEffect(()=>{localStorage.setItem('velora-config',JSON.stringify({color,wheel,interior}))},[color,wheel,interior]);
  useEffect(()=>{gsap.registerPlugin(ScrollTrigger); const ctx=gsap.context(()=>{gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.fromTo(el,{y:52,opacity:0},{y:0,opacity:1,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 86%'}}));gsap.to('.reveal-car',{scale:1.13,yPercent:5,scrollTrigger:{trigger:'.scroll-story',start:'top top',end:'bottom bottom',scrub:1.2}})},root);return()=>ctx.revert()},[]);
  function launch(){setSpeed(0);const start=performance.now();const tick=(t:number)=>{const n=Math.min(60,Math.round((t-start)/48));setSpeed(n);if(n<60)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
  const baseRange=mode==='Eco'?430:mode==='Dynamic'?365:410; const estimated=Math.round(baseRange-Math.abs(temperature-68)*.55);
  return <div ref={root} className="site-shell"><AnimatePresence>{!loaded&&<motion.div className="preloader" exit={{opacity:0}} transition={{duration:.45}}><motion.span initial={{opacity:0,letterSpacing:'.8em'}} animate={{opacity:1,letterSpacing:'.42em'}} transition={{duration:.55}}>VELORA</motion.span><i><motion.b initial={{scaleX:0}} animate={{scaleX:1}} transition={{duration:.72,ease:[.76,0,.24,1]}}/></i></motion.div>}</AnimatePresence><a className="skip" href="#main">Skip to content</a><motion.div className="scroll-progress" style={{scaleX:progress}}/>
    <header className={`nav ${scrolled?'scrolled':''}`}><a className="wordmark" href="/">VELORA</a><nav className="desktop-nav">{['V12','Design','Performance','Interior','Technology','Configure'].map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav><div className="nav-actions"><button className="reserve-small" onClick={()=>setModal(true)}>Reserve V12</button><button aria-label="Open menu" className="menu-button" onClick={()=>setMenu(true)}><Menu/></button></div></header>
    <AnimatePresence>{menu&&<motion.div className="mobile-menu" initial={{clipPath:'inset(0 0 100% 0)'}} animate={{clipPath:'inset(0 0 0% 0)'}} exit={{clipPath:'inset(0 0 100% 0)'}}><span className="menu-mark">VELORA <i>V12</i></span><button aria-label="Close menu" onClick={()=>setMenu(false)}><X/></button>{['V12','Design','Performance','Interior','Technology','Configure','Reserve'].map((x,i)=><motion.a key={x} initial={{x:-30,opacity:0}} animate={{x:0,opacity:1}} transition={{delay:.05*i,type:'spring',stiffness:210,damping:24}} href={`#${x.toLowerCase()}`} onClick={()=>setMenu(false)}>{x}<span>0{i+1}</span></motion.a>)}<small>Motion, refined.</small></motion.div>}</AnimatePresence>
    <main id="main"><section id="v12" className="hero"><div className="hero-glow"/><motion.div className="hero-copy" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.25,duration:1}}><p className="eyebrow">The electric grand tourer</p><h1>VELORA <i>V12</i></h1><p>Motion, refined.</p><div className="hero-buttons"><MagneticButton>Experience V12</MagneticButton><MagneticButton dark onClick={()=>document.querySelector('#configure')?.scrollIntoView({behavior:'smooth'})}>Configure yours</MagneticButton></div></motion.div><motion.div className="car-stage" style={{y:heroY}}><img src="/velora-v12.png" alt="VELORA V12 fictional electric grand tourer in an obsidian studio"/><div className="paint-wash" style={{background:selected}}/></motion.div><div className="hero-specs"><div><strong>2.9</strong><span>sec · 0–60</span></div><div><strong>410</strong><span>mile range</span></div><div><strong>780</strong><span>horsepower</span></div></div><div className="fictional">Fictional concept specifications</div></section>
    <section id="design" className="scroll-story"><div className="sticky-scene"><div className="story-index">01 — AERODYNAMICS</div><div className="story-copy"><p>Sculpted by airflow.</p><h2>Presence,<br/>without <em>noise.</em></h2></div><div className="scene-rail">{scenes.map(([n,label])=><div key={n}><span>{n}</span><p>{label}</p></div>)}</div><img className="reveal-car" src="/velora-v12.png" alt="VELORA V12 side profile"/><div className="aero-line"/></div></section>
    <section id="performance" className="performance"><div className="section-head reveal"><p className="eyebrow">Performance · 02</p><h2>Power you feel.<br/><span>Silence you notice.</span></h2></div><div className="metric-grid reveal"><div><strong>780</strong><small>hp</small><p>Dual-motor electric architecture.</p></div><div><strong>2.9</strong><small>s</small><p>Zero to sixty, without drama.</p></div><div><strong>410</strong><small>mi</small><p>Effortless estimated range.</p></div></div><div className="launch-card reveal"><div><p className="eyebrow">Acceleration experience</p><h3>{speed}<span> mph</span></h3><div className="speed-track"><motion.i animate={{width:`${speed/60*100}%`}}/></div></div><button onClick={launch}><Play fill="currentColor"/> Start</button></div><p className="demo-note">All performance values are fictional portfolio data.</p></section>
    <section id="configure" className="configurator"><div className="config-visual"><div className="config-label"><span>V12</span><b>{color}</b></div><img src="/velora-v12.png" alt={`VELORA V12 in ${color}`}/><motion.div className="paint-wash config-wash" animate={{backgroundColor:selected}}/></div><div className="config-panel"><p className="eyebrow">Make it yours · 03</p><h2>Configure V12</h2><p className="config-sub">A study in personal expression.</p><h4>Exterior finish <span>{color}</span></h4><div className="swatches">{colors.map(([name,hex])=><button aria-label={name} title={name} key={name} onClick={()=>setColor(name)} className={color===name?'active':''} style={{background:hex}}/>)}</div><h4>Wheels <span>{wheel}</span></h4><div className="option-row">{['Aero 21','Performance 22','Touring 21'].map(x=><button key={x} className={wheel===x?'selected':''} onClick={()=>setWheel(x)}>{x}</button>)}</div><h4>Interior <span>{interior}</span></h4><div className="option-row">{['Onyx','Ivory','Cognac','Graphite'].map(x=><button key={x} className={interior===x?'selected':''} onClick={()=>setInterior(x)}>{x}</button>)}</div><div className="price"><p>Estimated configuration <small>Fictional demo pricing</small></p><strong>$146,800</strong></div><MagneticButton onClick={()=>setModal(true)}>Reserve this V12</MagneticButton></div></section>
    <section id="interior" className="interior"><div className="interior-backdrop"/><div className="interior-copy reveal"><p className="eyebrow">The cabin · 04</p><h2>A quieter kind<br/>of <em>luxury.</em></h2><p>Every surface, control, and source of light is considered around one idea: helping distance disappear.</p></div><div className="interior-features reveal">{['Panoramic display','Tactile natural materials','Four-zone intelligent climate'].map((x,i)=><div key={x}><span>0{i+1}</span><p>{x}</p><MoveRight/></div>)}</div></section>
    <section id="technology" className="technology"><div className="section-head light reveal"><p className="eyebrow">Technology · 05</p><h2>Technology that disappears<br/><span>into the experience.</span></h2></div><div className="tech-grid">{tech.map(([n,title,copy])=><motion.article tabIndex={0} key={n} whileHover={{y:-8}} transition={{type:'spring',stiffness:250,damping:20}}><span>{n}</span><div className="tech-icon">{n==='01'?<Gauge/>:n==='02'?<ArrowDownRight/>:n==='03'?<Zap/>:<BatteryCharging/>}</div><h3>{title}</h3><p>{copy}</p><ChevronRight/></motion.article>)}</div></section>
    <section className="range"><div className="range-copy reveal"><p className="eyebrow">Go further · 06</p><h2><motion.span key={estimated} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}>{estimated} miles.</motion.span><br/><em>One intention.</em></h2><p>A grand tourer built around long horizons. Tune the fictional estimate to the journey ahead.</p><div className="range-controls"><label>Drive mode <span>{mode}</span><div>{['Eco','Touring','Dynamic'].map(x=><button className={mode===x?'active':''} key={x} onClick={()=>setMode(x)}>{x}</button>)}</div></label><label>Temperature <span>{temperature}°F</span><input aria-label="Temperature" type="range" min="0" max="110" value={temperature} onChange={e=>setTemperature(Number(e.target.value))}/></label></div><small className="range-disclaimer">Fictional estimate · actual range varies</small></div><div className="range-ring reveal"><span>10—80%</span><strong>21</strong><small>minutes</small><i>Demo estimate</i></div></section>
    <section id="reserve" className="closing"><img src="/velora-v12.png" alt="VELORA V12 in cinematic darkness"/><div className="closing-copy reveal"><p className="eyebrow">Private preview</p><h2>Your V12<br/><em>awaits.</em></h2><p>Begin a private conversation with a VELORA concierge.</p><div><MagneticButton onClick={()=>document.querySelector('#configure')?.scrollIntoView({behavior:'smooth'})}>Configure V12</MagneticButton><MagneticButton dark onClick={()=>setModal(true)}>Reserve a preview</MagneticButton></div></div></section></main>
    <footer><a className="wordmark" href="#v12">VELORA</a><p>VELORA is a fictional automotive brand created as a portfolio concept.</p><div><a href="/about">About</a><a href="/privacy">Privacy</a><a href="#configure">Configure</a></div><small>© 2026 VELORA CONCEPT</small></footer>
    <AnimatePresence>{modal&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setModal(false)}><motion.div role="dialog" aria-modal="true" aria-label="Reserve a private preview" className="modal" initial={{y:60,opacity:0,scale:.97}} animate={{y:0,opacity:1,scale:1}} exit={{y:40,opacity:0}} transition={{type:'spring',stiffness:260,damping:25}} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(false)} aria-label="Close"><X/></button>{submitted?<div className="success"><span>V</span><h2>Consider it noted.</h2><p>A fictional VELORA concierge would be in touch shortly.</p><MagneticButton onClick={()=>setModal(false)}>Return to V12</MagneticButton></div>:<><p className="eyebrow">Private preview</p><h2>Reserve your<br/>VELORA V12.</h2><form onSubmit={e=>{e.preventDefault();setSubmitted(true)}}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Phone<input placeholder="+1 000 000 0000"/></label><label>Preferred city<input placeholder="New York"/></label><label className="wide">Message<textarea placeholder="Tell us how you imagine your V12."/></label><button type="submit" className="submit">Request private preview <ArrowRight/></button></form><small>Portfolio concept — no real reservation will be made.</small></>}</motion.div></motion.div>}</AnimatePresence>
  </div>;
}
